import { useEffect, useState } from 'react';
import { getStoredToken, type AuthUser } from '../services/auth';
import {
  fetchIncidentEvidence,
  fetchIncidents,
  formatIncidentStatus,
  updateIncidentStatus,
  type Incident,
  type IncidentEvidence,
  type IncidentStatus,
} from '../services/incidents';
import type { Alert, SecuritySeverity } from '../services/dashboard';
import type { SecurityEventRecord } from '../services/events';

type IncidentsPageProps = {
  user: AuthUser;
  navItems: string[];
  onLogout: () => void;
  onNavigate: (page: string) => void;
  selectedIncidentId?: string;
  apiError?: string | null;
  realtimeVersion?: number;
  realtimeStatus?: 'LIVE' | 'RECONNECTING';
};

const severityClass: Record<SecuritySeverity, string> = {
  LOW: 'border-slate-600 bg-slate-800 text-slate-300',
  MEDIUM: 'border-sky-500/40 bg-sky-500/10 text-sky-300',
  HIGH: 'border-amber-500/40 bg-amber-500/10 text-amber-300',
  CRITICAL: 'border-rose-500/50 bg-rose-500/15 text-rose-200',
};
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
const statusOptions: Array<IncidentStatus | 'OPEN' | 'ALL'> = ['ALL', 'OPEN', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE'];

export function IncidentsPage(props: IncidentsPageProps) {
  return props.selectedIncidentId ? <IncidentDetail {...props} /> : <IncidentList {...props} />;
}

function Shell({ children, title, eyebrow, active, user, navItems, onLogout, onNavigate, apiError }: IncidentsPageProps & { children: React.ReactNode; title: string; eyebrow: string; active: string }) {
  return <div className="min-h-screen bg-slate-950 text-slate-100"><aside className="fixed left-0 top-0 hidden h-full w-72 border-r border-slate-800 bg-slate-900/95 p-6 lg:block"><div className="mb-8 inline-flex items-center rounded-full border border-sky-500/40 bg-sky-500/10 px-3 py-2 text-xs font-semibold uppercase tracking-[0.25em] text-sky-300">AI-SOC</div><nav className="space-y-2">{navItems.map((item) => <button key={item} type="button" onClick={() => onNavigate(item)} className={`flex w-full items-center justify-between rounded-xl border px-3 py-2 text-left text-sm transition ${item === active ? 'border-sky-500/50 bg-sky-500/10 text-white' : 'border-slate-800 bg-slate-950/70 text-slate-200 hover:border-sky-500/40 hover:text-white'}`}>{item}<span className="text-xs text-slate-400">→</span></button>)}</nav><div className="mt-10 rounded-xl border border-slate-800 bg-slate-950/70 p-4"><div className="text-xs uppercase tracking-[0.25em] text-slate-400">Signed in</div><div className="mt-3 text-lg font-semibold text-white">{user.username}</div><div className="text-sm text-slate-300">{user.email}</div><div className="mt-2 inline-flex rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-1 text-xs text-emerald-300">{user.role}</div></div></aside><main className="min-h-screen p-4 sm:p-8 lg:ml-72"><header className="mb-4 flex flex-col gap-4 rounded-2xl border border-slate-800 bg-slate-900/80 p-5 sm:flex-row sm:items-center sm:justify-between lg:mb-8"><div><p className="text-sm uppercase tracking-[0.3em] text-slate-400">{eyebrow}</p><h1 className="mt-2 text-3xl font-bold text-white">{title}</h1></div><button type="button" onClick={onLogout} className="self-start rounded-xl border border-slate-700 bg-slate-950 px-4 py-2 text-sm font-medium text-slate-100 hover:border-sky-500/40 hover:text-sky-200 sm:self-auto">Logout</button></header><nav className="mb-6 flex gap-2 overflow-x-auto lg:hidden">{navItems.map((item) => <button key={item} type="button" onClick={() => onNavigate(item)} className={`shrink-0 rounded-lg border px-3 py-2 text-xs font-semibold ${item === active ? 'border-sky-500/50 bg-sky-500/10 text-white' : 'border-slate-800 bg-slate-900 text-slate-400'}`}>{item}</button>)}</nav>{(apiError) && <div className="mb-6 rounded-xl border border-rose-500/40 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{apiError}</div>}{children}</main></div>;
}

function IncidentList(props: IncidentsPageProps) {
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [filters, setFilters] = useState({ status: 'ALL', severity: 'ALL', risk: 'ALL', time: 'ALL' });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const token = getStoredToken(); if (!token) { setError('Your session has expired. Please sign in again.'); setLoading(false); return; } setLoading(true); fetchIncidents(token, filters).then((result) => setIncidents(result.incidents)).catch((requestError: unknown) => setError(requestError instanceof Error ? requestError.message : 'Unable to load incidents.')).finally(() => setLoading(false)); }, [filters, props.realtimeVersion]);
  const setFilter = (key: keyof typeof filters, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  return <Shell {...props} title="Incidents" eyebrow="Investigation queue" active="Incidents"><section className="mb-6 rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Correlated cases</div><div className="mt-2 text-2xl font-bold text-white">{incidents.length} incidents in view</div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{([['status', 'Status'], ['severity', 'Severity'], ['risk', 'Risk'], ['time', 'Time']] as const).map(([key, label]) => <label key={key} className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-400">{label}<select value={filters[key]} onChange={(event) => setFilter(key, event.target.value)} className="mt-2 block w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm font-normal tracking-normal text-white outline-none focus:border-sky-500">{(key === 'status' ? statusOptions : key === 'severity' ? ['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] : key === 'risk' ? ['ALL', 'HIGH', 'MEDIUM', 'LOW'] : ['ALL', '24H', '7D']).map((option) => <option key={option} value={option}>{option === 'ALL' ? `All ${label.toLowerCase()}` : option === 'OPEN' ? 'Open' : option}</option>)}</select></label>)}</div></div></section>{error && <div className="mb-6 rounded-xl border border-rose-500/40 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{error}</div>}{loading ? <Panel>Loading incident queue...</Panel> : incidents.length === 0 ? <Panel>No incidents match the selected filters.</Panel> : <div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/80">{incidents.map((incident) => <button key={incident.id} type="button" onClick={() => props.onNavigate(`Incident:${incident.id}`)} className="grid w-full gap-4 border-b border-slate-800 px-5 py-5 text-left transition last:border-0 hover:bg-slate-800/50 md:grid-cols-[minmax(0,1.7fr)_110px_110px_130px_100px] md:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-xs text-sky-300">{incident.incidentId}</span><span className={`rounded-full border px-2 py-1 text-xs font-semibold ${severityClass[incident.severity]}`}>{incident.severity}</span></div><div className="mt-2 truncate font-semibold text-white">{incident.title}</div><div className="mt-1 truncate text-sm text-slate-400">{incident.sourceIps.join(' · ') || 'Source unavailable'}</div></div><Metric label="Risk" value={`${incident.riskScore}/100`} emphasize={incident.riskScore >= 70} /><Metric label="Status" value={formatIncidentStatus(incident.status)} /><Metric label="Evidence" value={`${incident.relatedAlertIds.length} alerts · ${incident.relatedEventIds.length} events`} /><time className="text-sm text-slate-400" dateTime={incident.createdAt}>{formatDate(incident.createdAt)}</time></button>)}</div>}</Shell>;
}

function IncidentDetail(props: IncidentsPageProps) {
  const [evidence, setEvidence] = useState<IncidentEvidence | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [updating, setUpdating] = useState(false);
  useEffect(() => { const token = getStoredToken(); if (!token || !props.selectedIncidentId) return; setLoading(true); fetchIncidentEvidence(token, props.selectedIncidentId).then(setEvidence).catch((requestError: unknown) => setError(requestError instanceof Error ? requestError.message : 'Unable to load incident evidence.')).finally(() => setLoading(false)); }, [props.selectedIncidentId, props.realtimeVersion]);
  const changeStatus = async (status: IncidentStatus) => { if (!evidence) return; const token = getStoredToken(); if (!token) return; setUpdating(true); setError(null); try { const incident = await updateIncidentStatus(token, evidence.incident.id, status); setEvidence({ ...evidence, incident }); } catch (requestError: unknown) { setError(requestError instanceof Error ? requestError.message : 'Unable to update incident status.'); } finally { setUpdating(false); } };
  return <Shell {...props} title={evidence?.incident.title || 'Incident investigation'} eyebrow="Case review" active="Incidents"><button type="button" onClick={() => props.onNavigate('Incidents')} className="mb-6 text-sm text-sky-300 hover:text-white">← Back to incidents</button>{error && <div className="mb-6 rounded-xl border border-rose-500/40 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{error}</div>}{loading ? <Panel>Loading investigation evidence...</Panel> : !evidence ? <Panel>Incident evidence is unavailable.</Panel> : <><InvestigationHeader incident={evidence.incident} canUpdate={props.user.role !== 'VIEWER'} updating={updating} onStatusChange={changeStatus} /><div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><section><PanelTitle>Attack timeline <span>{evidence.events.length} events</span></PanelTitle><Timeline events={evidence.events} alerts={evidence.alerts} /></section><aside className="space-y-6"><EvidencePanel incident={evidence.incident} rules={evidence.rules} /><AlertPanel alerts={evidence.alerts} /></aside></div><section className="mt-6"><PanelTitle>Security event evidence <span>{evidence.events.length} records</span></PanelTitle><EventEvidence events={evidence.events} /></section></>}</Shell>;
}

function InvestigationHeader({ incident, canUpdate, updating, onStatusChange }: { incident: Incident; canUpdate: boolean; updating: boolean; onStatusChange: (status: IncidentStatus) => void }) { return <section className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><div className="flex flex-col justify-between gap-5 lg:flex-row"><div><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-xs text-sky-300">{incident.incidentId}</span><span className={`rounded-full border px-2 py-1 text-xs font-semibold ${severityClass[incident.severity]}`}>{incident.severity}</span></div><h2 className="mt-3 text-2xl font-bold text-white">{incident.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{incident.description}</p></div><div className="flex flex-col items-start gap-3 lg:items-end"><div className="text-4xl font-bold text-amber-300">{incident.riskScore}<span className="text-base font-medium text-slate-500"> / 100 risk</span></div>{canUpdate ? <select disabled={updating} value={incident.status} onChange={(event) => onStatusChange(event.target.value as IncidentStatus)} className="rounded-lg border border-sky-500/40 bg-slate-950 px-3 py-2 text-sm text-white"><option value="NEW">OPEN</option><option value="INVESTIGATING">INVESTIGATING</option><option value="RESOLVED">RESOLVED</option><option value="FALSE_POSITIVE">FALSE POSITIVE</option></select> : <span className="rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300">{formatIncidentStatus(incident.status)}</span>}</div></div><div className="mt-6 grid gap-4 border-t border-slate-800 pt-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><Metric label="Source IPs" value={incident.sourceIps.join(', ') || 'None'} /><Metric label="Users" value={incident.affectedUsers.join(', ') || 'None'} /><Metric label="First seen" value={formatDate(incident.firstSeen)} /><Metric label="Updated" value={formatDate(incident.updatedAt)} /></div></section>; }

function Timeline({ events, alerts }: { events: SecurityEventRecord[]; alerts: Alert[] }) { const alertEvents = new Set(alerts.map((alert) => alert.eventId)); return <div className="relative ml-2 border-l border-slate-700 py-2">{[...events].sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()).map((event, index) => <div key={event.id} className="relative pb-6 pl-7 last:pb-2"><span className={`absolute -left-[7px] top-1 h-3 w-3 rounded-full border-2 border-slate-950 ${alertEvents.has(event.id) ? 'bg-amber-300' : 'bg-sky-400'}`} /><div className="rounded-xl border border-slate-800 bg-slate-900/80 p-4"><div className="flex flex-wrap justify-between gap-3"><div className="font-semibold text-white">{event.eventType}</div><time className="text-xs text-slate-500">{formatDate(event.timestamp)}</time></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-400"><span>{event.sourceIp || 'No IP'}</span><span>{event.username || 'No user'}</span><span className={severityClass[event.severity].split(' ').pop()}>{event.severity}</span>{alertEvents.has(event.id) && <span className="text-amber-300">Alert signal</span>}</div><div className="mt-2 text-sm text-slate-400">{event.message || event.action || 'No additional event context.'}</div></div>{index < events.length - 1 && <div className="absolute -bottom-1 left-[-5px] text-[10px] text-slate-600">↓</div>}</div>)}</div>; }

function EvidencePanel({ incident, rules }: { incident: Incident; rules: Array<{ id: string; name: string; riskScore: number; severity: SecuritySeverity }> }) { return <section className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><PanelTitle>Investigation context</PanelTitle><div className="space-y-4 text-sm"><div><div className="text-xs uppercase tracking-[0.16em] text-slate-500">Detection rules</div>{rules.length ? rules.map((rule) => <div key={rule.id} className="mt-2 flex justify-between gap-3 text-slate-200"><span>{rule.name}</span><span className="text-amber-300">{rule.riskScore} risk</span></div>) : <div className="mt-2 text-slate-500">No rule details available.</div>}</div><div><div className="text-xs uppercase tracking-[0.16em] text-slate-500">Source IPs</div><div className="mt-2 font-mono text-sky-300">{incident.sourceIps.join(' · ') || 'None recorded'}</div></div></div></section>; }

function AlertPanel({ alerts }: { alerts: Alert[] }) { return <section className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5"><PanelTitle>Alert signals <span>{alerts.length}</span></PanelTitle><div className="space-y-3">{alerts.length ? alerts.map((alert) => <div key={alert.id} className="rounded-xl border border-slate-800 bg-slate-950/60 p-3"><div className="flex justify-between gap-3"><span className="text-sm font-semibold text-white">{alert.title}</span><span className="text-sm text-amber-300">{alert.riskScore}</span></div><div className="mt-1 text-xs text-slate-500">{alert.eventType} · {formatDate(alert.triggeredAt)}</div>{alert.metadata?.detectionType === 'ML_ANOMALY' && <div className="mt-3 border-t border-slate-800 pt-3 text-xs text-amber-200"><div className="font-semibold">ML anomaly detected</div><div className="mt-1">Anomaly score: {Number(alert.metadata.anomalyScore).toFixed(2)} · Threshold: 0.65</div><div className="mt-1 text-slate-500">Model: {String(alert.metadata.modelVersion)}</div></div>}</div>) : <div className="text-sm text-slate-500">No related alerts returned.</div>}</div></section>; }

function EventEvidence({ events }: { events: SecurityEventRecord[] }) { return <div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/80">{events.map((event) => <div key={event.id} className="grid gap-3 border-b border-slate-800 px-5 py-4 last:border-0 md:grid-cols-[150px_150px_1fr] md:items-start"><time className="text-sm text-slate-500">{formatDate(event.timestamp)}</time><div><div className="font-semibold text-white">{event.eventType}</div><div className="mt-1 text-xs text-slate-500">{event.sourceIp || 'No source IP'}</div></div><div className="text-sm text-slate-400">{event.message || event.action || 'No message recorded'}{event.username && <span className="ml-2 text-sky-300">user: {event.username}</span>}</div></div>)}</div>; }
function Panel({ children }: { children: React.ReactNode }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-8 text-slate-400">{children}</div>; }
function PanelTitle({ children }: { children: React.ReactNode }) { return <div className="mb-4 flex items-center justify-between border-b border-slate-800 pb-4 text-sm font-semibold uppercase tracking-[0.18em] text-slate-300">{children}</div>; }
function Metric({ label, value, emphasize = false }: { label: string; value: string; emphasize?: boolean }) { return <div className="min-w-0"><div className="text-xs uppercase tracking-[0.14em] text-slate-500">{label}</div><div className={`mt-1 truncate text-sm font-semibold ${emphasize ? 'text-amber-300' : 'text-slate-200'}`}>{value}</div></div>; }
